In [1]:
import pandas as pd

In [2]:
d={
    'movies':['KGF', 'Don', 'Mark','Loka','VIP','Bahubali','Kantara','RRR','Mastani','Shaitan'],
    'rating':[8,6,None,7,None,7,8,None,6,7],
    'Language_year':['kannada-2018','Hindi-2010','Kannnada-2020','Telagu-2020','Telagu-2022','Hindi-2019','Kannada-2021','Telagu-2024','Hindi-2019','Hindi-2022'],
    'Cast':[['Yash','Rfst'],['SRK','Sdfghjk'],['Sudeep','Dfgh'],['Nelson','Jkhf'],['Dhanush','Gjkk'],['Rishab','Fghyg'],['NTR','Hytf'],['Ranveer','Gfdr'],['Salmaan','Iuyt'],['SOmeone','Kiuy']],
    'Hotstar':[1,1,1,0,0,1,1,1,0,0],
    'Netflix':['N','Y','N','Y','Y','N','Y','N','Y','Y']

}

In [3]:
df=pd.DataFrame(d)

In [4]:
df

     movies  rating  Language_year             Cast  Hotstar Netflix
0       KGF     8.0   kannada-2018     [Yash, Rfst]        1       N
1       Don     6.0     Hindi-2010   [SRK, Sdfghjk]        1       Y
2      Mark     NaN  Kannnada-2020   [Sudeep, Dfgh]        1       N
3      Loka     7.0    Telagu-2020   [Nelson, Jkhf]        0       Y
4       VIP     NaN    Telagu-2022  [Dhanush, Gjkk]        0       Y
5  Bahubali     7.0     Hindi-2019  [Rishab, Fghyg]        1       N
6   Kantara     8.0   Kannada-2021      [NTR, Hytf]        1       Y
7       RRR     NaN    Telagu-2024  [Ranveer, Gfdr]        1       N
8   Mastani     6.0     Hindi-2019  [Salmaan, Iuyt]        0       Y
9   Shaitan     7.0     Hindi-2022  [SOmeone, Kiuy]        0       Y

In [5]:
df.head

<bound method NDFrame.head of      movies  rating  Language_year             Cast  Hotstar Netflix
0       KGF     8.0   kannada-2018     [Yash, Rfst]        1       N
1       Don     6.0     Hindi-2010   [SRK, Sdfghjk]        1       Y
2      Mark     NaN  Kannnada-2020   [Sudeep, Dfgh]        1       N
3      Loka     7.0    Telagu-2020   [Nelson, Jkhf]        0       Y
4       VIP     NaN    Telagu-2022  [Dhanush, Gjkk]        0       Y
5  Bahubali     7.0     Hindi-2019  [Rishab, Fghyg]        1       N
6   Kantara     8.0   Kannada-2021      [NTR, Hytf]        1       Y
7       RRR     NaN    Telagu-2024  [Ranveer, Gfdr]        1       N
8   Mastani     6.0     Hindi-2019  [Salmaan, Iuyt]        0       Y
9   Shaitan     7.0     Hindi-2022  [SOmeone, Kiuy]        0       Y>

In [6]:
df.head()

  movies  rating  Language_year             Cast  Hotstar Netflix
0    KGF     8.0   kannada-2018     [Yash, Rfst]        1       N
1    Don     6.0     Hindi-2010   [SRK, Sdfghjk]        1       Y
2   Mark     NaN  Kannnada-2020   [Sudeep, Dfgh]        1       N
3   Loka     7.0    Telagu-2020   [Nelson, Jkhf]        0       Y
4    VIP     NaN    Telagu-2022  [Dhanush, Gjkk]        0       Y

In [7]:
df.tail()

     movies  rating Language_year             Cast  Hotstar Netflix
5  Bahubali     7.0    Hindi-2019  [Rishab, Fghyg]        1       N
6   Kantara     8.0  Kannada-2021      [NTR, Hytf]        1       Y
7       RRR     NaN   Telagu-2024  [Ranveer, Gfdr]        1       N
8   Mastani     6.0    Hindi-2019  [Salmaan, Iuyt]        0       Y
9   Shaitan     7.0    Hindi-2022  [SOmeone, Kiuy]        0       Y

In [8]:
df.T

,0,1,2,3,4,5,6,7,8,9
movies,KGF,Don,Mark,Loka,VIP,Bahubali,Kantara,RRR,Mastani,Shaitan
rating,8.0,6.0,NaN,7.0,NaN,7.0,8.0,NaN,6.0,7.0
Language_year,kannada-2018,Hindi-2010,Kannnada-2020,Telagu-2020,Telagu-2022,Hindi-2019,Kannada-2021,Telagu-2024,Hindi-2019,Hindi-2022
Cast,"[Yash, Rfst]","[SRK, Sdfghjk]","[Sudeep, Dfgh]","[Nelson, Jkhf]","[Dhanush, Gjkk]","[Rishab, Fghyg]","[NTR, Hytf]","[Ranveer, Gfdr]","[Salmaan, Iuyt]","[SOmeone, Kiuy]"
Hotstar,1,1,1,0,0,1,1,1,0,0
Netflix,N,Y,N,Y,Y,N,Y,N,Y,Y

In [9]:
df.head(10)

     movies  rating  Language_year             Cast  Hotstar Netflix
0       KGF     8.0   kannada-2018     [Yash, Rfst]        1       N
1       Don     6.0     Hindi-2010   [SRK, Sdfghjk]        1       Y
2      Mark     NaN  Kannnada-2020   [Sudeep, Dfgh]        1       N
3      Loka     7.0    Telagu-2020   [Nelson, Jkhf]        0       Y
4       VIP     NaN    Telagu-2022  [Dhanush, Gjkk]        0       Y
5  Bahubali     7.0     Hindi-2019  [Rishab, Fghyg]        1       N
6   Kantara     8.0   Kannada-2021      [NTR, Hytf]        1       Y
7       RRR     NaN    Telagu-2024  [Ranveer, Gfdr]        1       N
8   Mastani     6.0     Hindi-2019  [Salmaan, Iuyt]        0       Y
9   Shaitan     7.0     Hindi-2022  [SOmeone, Kiuy]        0       Y

In [10]:
df.head(7)

     movies  rating  Language_year             Cast  Hotstar Netflix
0       KGF     8.0   kannada-2018     [Yash, Rfst]        1       N
1       Don     6.0     Hindi-2010   [SRK, Sdfghjk]        1       Y
2      Mark     NaN  Kannnada-2020   [Sudeep, Dfgh]        1       N
3      Loka     7.0    Telagu-2020   [Nelson, Jkhf]        0       Y
4       VIP     NaN    Telagu-2022  [Dhanush, Gjkk]        0       Y
5  Bahubali     7.0     Hindi-2019  [Rishab, Fghyg]        1       N
6   Kantara     8.0   Kannada-2021      [NTR, Hytf]        1       Y

In [11]:
df

     movies  rating  Language_year             Cast  Hotstar Netflix
0       KGF     8.0   kannada-2018     [Yash, Rfst]        1       N
1       Don     6.0     Hindi-2010   [SRK, Sdfghjk]        1       Y
2      Mark     NaN  Kannnada-2020   [Sudeep, Dfgh]        1       N
3      Loka     7.0    Telagu-2020   [Nelson, Jkhf]        0       Y
4       VIP     NaN    Telagu-2022  [Dhanush, Gjkk]        0       Y
5  Bahubali     7.0     Hindi-2019  [Rishab, Fghyg]        1       N
6   Kantara     8.0   Kannada-2021      [NTR, Hytf]        1       Y
7       RRR     NaN    Telagu-2024  [Ranveer, Gfdr]        1       N
8   Mastani     6.0     Hindi-2019  [Salmaan, Iuyt]        0       Y
9   Shaitan     7.0     Hindi-2022  [SOmeone, Kiuy]        0       Y

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   movies         10 non-null     object
 1   rating         7 non-null      float64
 2   Language_year  10 non-null     object
 3   Cast           10 non-null     object
 4   Hotstar        10 non-null     int64
 5   Netflix        10 non-null     object
dtypes: float64(1), int64(1), object(4)
memory usage: 608.0+ bytes

### The info() fucntion gives the details of a particular DataFrame

In [13]:
df['movies']

0         KGF
1         Don
2        Mark
3        Loka
4         VIP
5    Bahubali
6     Kantara
7         RRR
8     Mastani
9     Shaitan
Name: movies, dtype: object

### When we have to pass the multiple columns then we have to pass it in list

In [14]:
df[['movies','Cast']]

     movies             Cast
0       KGF     [Yash, Rfst]
1       Don   [SRK, Sdfghjk]
2      Mark   [Sudeep, Dfgh]
3      Loka   [Nelson, Jkhf]
4       VIP  [Dhanush, Gjkk]
5  Bahubali  [Rishab, Fghyg]
6   Kantara      [NTR, Hytf]
7       RRR  [Ranveer, Gfdr]
8   Mastani  [Salmaan, Iuyt]
9   Shaitan  [SOmeone, Kiuy]

### To select particulr rreccord of the data then

In [15]:
df[df['movies']=='RRR']

  movies  rating Language_year             Cast  Hotstar Netflix
7    RRR     NaN   Telagu-2024  [Ranveer, Gfdr]        1       N

In [16]:
df

     movies  rating  Language_year             Cast  Hotstar Netflix
0       KGF     8.0   kannada-2018     [Yash, Rfst]        1       N
1       Don     6.0     Hindi-2010   [SRK, Sdfghjk]        1       Y
2      Mark     NaN  Kannnada-2020   [Sudeep, Dfgh]        1       N
3      Loka     7.0    Telagu-2020   [Nelson, Jkhf]        0       Y
4       VIP     NaN    Telagu-2022  [Dhanush, Gjkk]        0       Y
5  Bahubali     7.0     Hindi-2019  [Rishab, Fghyg]        1       N
6   Kantara     8.0   Kannada-2021      [NTR, Hytf]        1       Y
7       RRR     NaN    Telagu-2024  [Ranveer, Gfdr]        1       N
8   Mastani     6.0     Hindi-2019  [Salmaan, Iuyt]        0       Y
9   Shaitan     7.0     Hindi-2022  [SOmeone, Kiuy]        0       Y

In [17]:
df['movie']=df['movies'].str.title()

In [18]:
df

     movies  rating  Language_year             Cast  Hotstar Netflix     movie
0       KGF     8.0   kannada-2018     [Yash, Rfst]        1       N       Kgf
1       Don     6.0     Hindi-2010   [SRK, Sdfghjk]        1       Y       Don
2      Mark     NaN  Kannnada-2020   [Sudeep, Dfgh]        1       N      Mark
3      Loka     7.0    Telagu-2020   [Nelson, Jkhf]        0       Y      Loka
4       VIP     NaN    Telagu-2022  [Dhanush, Gjkk]        0       Y       Vip
5  Bahubali     7.0     Hindi-2019  [Rishab, Fghyg]        1       N  Bahubali
6   Kantara     8.0   Kannada-2021      [NTR, Hytf]        1       Y   Kantara
7       RRR     NaN    Telagu-2024  [Ranveer, Gfdr]        1       N       Rrr
8   Mastani     6.0     Hindi-2019  [Salmaan, Iuyt]        0       Y   Mastani
9   Shaitan     7.0     Hindi-2022  [SOmeone, Kiuy]        0       Y   Shaitan

In [19]:
df.drop(columns=['movies'])

   rating  Language_year             Cast  Hotstar Netflix     movie
0     8.0   kannada-2018     [Yash, Rfst]        1       N       Kgf
1     6.0     Hindi-2010   [SRK, Sdfghjk]        1       Y       Don
2     NaN  Kannnada-2020   [Sudeep, Dfgh]        1       N      Mark
3     7.0    Telagu-2020   [Nelson, Jkhf]        0       Y      Loka
4     NaN    Telagu-2022  [Dhanush, Gjkk]        0       Y       Vip
5     7.0     Hindi-2019  [Rishab, Fghyg]        1       N  Bahubali
6     8.0   Kannada-2021      [NTR, Hytf]        1       Y   Kantara
7     NaN    Telagu-2024  [Ranveer, Gfdr]        1       N       Rrr
8     6.0     Hindi-2019  [Salmaan, Iuyt]        0       Y   Mastani
9     7.0     Hindi-2022  [SOmeone, Kiuy]        0       Y   Shaitan

In [20]:
df=df.drop(columns=['movies'])

In [21]:
df

   rating  Language_year             Cast  Hotstar Netflix     movie
0     8.0   kannada-2018     [Yash, Rfst]        1       N       Kgf
1     6.0     Hindi-2010   [SRK, Sdfghjk]        1       Y       Don
2     NaN  Kannnada-2020   [Sudeep, Dfgh]        1       N      Mark
3     7.0    Telagu-2020   [Nelson, Jkhf]        0       Y      Loka
4     NaN    Telagu-2022  [Dhanush, Gjkk]        0       Y       Vip
5     7.0     Hindi-2019  [Rishab, Fghyg]        1       N  Bahubali
6     8.0   Kannada-2021      [NTR, Hytf]        1       Y   Kantara
7     NaN    Telagu-2024  [Ranveer, Gfdr]        1       N       Rrr
8     6.0     Hindi-2019  [Salmaan, Iuyt]        0       Y   Mastani
9     7.0     Hindi-2022  [SOmeone, Kiuy]        0       Y   Shaitan

In [22]:
df=df.replace({'Y':1,'N':0})

C:\Users\idris\AppData\Local\Temp\ipykernel_20764\778951933.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df=df.replace({'Y':1,'N':0})

In [23]:
df

   rating  Language_year             Cast  Hotstar  Netflix     movie
0     8.0   kannada-2018     [Yash, Rfst]        1        0       Kgf
1     6.0     Hindi-2010   [SRK, Sdfghjk]        1        1       Don
2     NaN  Kannnada-2020   [Sudeep, Dfgh]        1        0      Mark
3     7.0    Telagu-2020   [Nelson, Jkhf]        0        1      Loka
4     NaN    Telagu-2022  [Dhanush, Gjkk]        0        1       Vip
5     7.0     Hindi-2019  [Rishab, Fghyg]        1        0  Bahubali
6     8.0   Kannada-2021      [NTR, Hytf]        1        1   Kantara
7     NaN    Telagu-2024  [Ranveer, Gfdr]        1        0       Rrr
8     6.0     Hindi-2019  [Salmaan, Iuyt]        0        1   Mastani
9     7.0     Hindi-2022  [SOmeone, Kiuy]        0        1   Shaitan

In [24]:
df['Language_year']=df['Language_year'].str.title()

In [25]:
df

   rating  Language_year             Cast  Hotstar  Netflix     movie
0     8.0   Kannada-2018     [Yash, Rfst]        1        0       Kgf
1     6.0     Hindi-2010   [SRK, Sdfghjk]        1        1       Don
2     NaN  Kannnada-2020   [Sudeep, Dfgh]        1        0      Mark
3     7.0    Telagu-2020   [Nelson, Jkhf]        0        1      Loka
4     NaN    Telagu-2022  [Dhanush, Gjkk]        0        1       Vip
5     7.0     Hindi-2019  [Rishab, Fghyg]        1        0  Bahubali
6     8.0   Kannada-2021      [NTR, Hytf]        1        1   Kantara
7     NaN    Telagu-2024  [Ranveer, Gfdr]        1        0       Rrr
8     6.0     Hindi-2019  [Salmaan, Iuyt]        0        1   Mastani
9     7.0     Hindi-2022  [SOmeone, Kiuy]        0        1   Shaitan

In [26]:
df[['Language','Year']]=df['Language_year'].str.split('-',expand=True)

In [27]:
df

,rating,Language_year,Cast,Hotstar,Netflix,movie,Language,Year
0,8.0,Kannada-2018,"[Yash, Rfst]",1,0,Kgf,Kannada,2018
1,6.0,Hindi-2010,"[SRK, Sdfghjk]",1,1,Don,Hindi,2010
2,NaN,Kannnada-2020,"[Sudeep, Dfgh]",1,0,Mark,Kannnada,2020
3,7.0,Telagu-2020,"[Nelson, Jkhf]",0,1,Loka,Telagu,2020
4,NaN,Telagu-2022,"[Dhanush, Gjkk]",0,1,Vip,Telagu,2022
5,7.0,Hindi-2019,"[Rishab, Fghyg]",1,0,Bahubali,Hindi,2019
6,8.0,Kannada-2021,"[NTR, Hytf]",1,1,Kantara,Kannada,2021
7,NaN,Telagu-2024,"[Ranveer, Gfdr]",1,0,Rrr,Telagu,2024
8,6.0,Hindi-2019,"[Salmaan, Iuyt]",0,1,Mastani,Hindi,2019
9,7.0,Hindi-2022,"[SOmeone, Kiuy]",0,1,Shaitan,Hindi,2022

In [28]:
df=df.drop(columns=['Language_year'])

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   rating    7 non-null      float64
 1   Cast      10 non-null     object
 2   Hotstar   10 non-null     int64
 3   Netflix   10 non-null     int64
 4   movie     10 non-null     object
 5   Language  10 non-null     object
 6   Year      10 non-null     object
dtypes: float64(1), int64(2), object(4)
memory usage: 688.0+ bytes

In [30]:
df=df.astype({'Year':'int64'})

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   rating    7 non-null      float64
 1   Cast      10 non-null     object
 2   Hotstar   10 non-null     int64
 3   Netflix   10 non-null     int64
 4   movie     10 non-null     object
 5   Language  10 non-null     object
 6   Year      10 non-null     int64
dtypes: float64(1), int64(3), object(3)
memory usage: 688.0+ bytes

In [32]:
df

   rating             Cast  Hotstar  Netflix     movie  Language  Year
0     8.0     [Yash, Rfst]        1        0       Kgf   Kannada  2018
1     6.0   [SRK, Sdfghjk]        1        1       Don     Hindi  2010
2     NaN   [Sudeep, Dfgh]        1        0      Mark  Kannnada  2020
3     7.0   [Nelson, Jkhf]        0        1      Loka    Telagu  2020
4     NaN  [Dhanush, Gjkk]        0        1       Vip    Telagu  2022
5     7.0  [Rishab, Fghyg]        1        0  Bahubali     Hindi  2019
6     8.0      [NTR, Hytf]        1        1   Kantara   Kannada  2021
7     NaN  [Ranveer, Gfdr]        1        0       Rrr    Telagu  2024
8     6.0  [Salmaan, Iuyt]        0        1   Mastani     Hindi  2019
9     7.0  [SOmeone, Kiuy]        0        1   Shaitan     Hindi  2022

In [33]:
df.loc[1]

rating                 6.0
Cast        [SRK, Sdfghjk]
Hotstar                  1
Netflix                  1
movie                  Don
Language             Hindi
Year                  2010
Name: 1, dtype: object

In [34]:
df.loc[[3,2,4,5]]

   rating             Cast  Hotstar  Netflix     movie  Language  Year
3     7.0   [Nelson, Jkhf]        0        1      Loka    Telagu  2020
2     NaN   [Sudeep, Dfgh]        1        0      Mark  Kannnada  2020
4     NaN  [Dhanush, Gjkk]        0        1       Vip    Telagu  2022
5     7.0  [Rishab, Fghyg]        1        0  Bahubali     Hindi  2019

In [35]:
df.loc[[1,4,7],['rating','movie','Year']]

   rating movie  Year
1     6.0   Don  2010
4     NaN   Vip  2022
7     NaN   Rrr  2024

In [36]:
df

   rating             Cast  Hotstar  Netflix     movie  Language  Year
0     8.0     [Yash, Rfst]        1        0       Kgf   Kannada  2018
1     6.0   [SRK, Sdfghjk]        1        1       Don     Hindi  2010
2     NaN   [Sudeep, Dfgh]        1        0      Mark  Kannnada  2020
3     7.0   [Nelson, Jkhf]        0        1      Loka    Telagu  2020
4     NaN  [Dhanush, Gjkk]        0        1       Vip    Telagu  2022
5     7.0  [Rishab, Fghyg]        1        0  Bahubali     Hindi  2019
6     8.0      [NTR, Hytf]        1        1   Kantara   Kannada  2021
7     NaN  [Ranveer, Gfdr]        1        0       Rrr    Telagu  2024
8     6.0  [Salmaan, Iuyt]        0        1   Mastani     Hindi  2019
9     7.0  [SOmeone, Kiuy]        0        1   Shaitan     Hindi  2022

In [37]:
df['Language']=='Kannada'

0     True
1    False
2    False
3    False
4    False
5    False
6     True
7    False
8    False
9    False
Name: Language, dtype: bool

In [38]:
df[df['Language']=='Kannada']

   rating          Cast  Hotstar  Netflix    movie Language  Year
0     8.0  [Yash, Rfst]        1        0      Kgf  Kannada  2018
6     8.0   [NTR, Hytf]        1        1  Kantara  Kannada  2021

In [39]:
df['Hotstar']==1

0     True
1     True
2     True
3    False
4    False
5     True
6     True
7     True
8    False
9    False
Name: Hotstar, dtype: bool

In [40]:
df[df['Language']=='Kannada']

   rating          Cast  Hotstar  Netflix    movie Language  Year
0     8.0  [Yash, Rfst]        1        0      Kgf  Kannada  2018
6     8.0   [NTR, Hytf]        1        1  Kantara  Kannada  2021

In [41]:
df.loc[(df['Language']=='Kannada') & (df['Hotstar']==1)]

   rating          Cast  Hotstar  Netflix    movie Language  Year
0     8.0  [Yash, Rfst]        1        0      Kgf  Kannada  2018
6     8.0   [NTR, Hytf]        1        1  Kantara  Kannada  2021

In [42]:
df[(df['Language']=='Kannada') & (df['Hotstar']==1)]

   rating          Cast  Hotstar  Netflix    movie Language  Year
0     8.0  [Yash, Rfst]        1        0      Kgf  Kannada  2018
6     8.0   [NTR, Hytf]        1        1  Kantara  Kannada  2021

In [43]:
df.loc[(df['Year']==2018) | (df['Year']==2022)]

   rating             Cast  Hotstar  Netflix    movie Language  Year
0     8.0     [Yash, Rfst]        1        0      Kgf  Kannada  2018
4     NaN  [Dhanush, Gjkk]        0        1      Vip   Telagu  2022
9     7.0  [SOmeone, Kiuy]        0        1  Shaitan    Hindi  2022

In [44]:
df[(df['Year']==2018) | (df['Year']==2022)]

   rating             Cast  Hotstar  Netflix    movie Language  Year
0     8.0     [Yash, Rfst]        1        0      Kgf  Kannada  2018
4     NaN  [Dhanush, Gjkk]        0        1      Vip   Telagu  2022
9     7.0  [SOmeone, Kiuy]        0        1  Shaitan    Hindi  2022

In [45]:
df

   rating             Cast  Hotstar  Netflix     movie  Language  Year
0     8.0     [Yash, Rfst]        1        0       Kgf   Kannada  2018
1     6.0   [SRK, Sdfghjk]        1        1       Don     Hindi  2010
2     NaN   [Sudeep, Dfgh]        1        0      Mark  Kannnada  2020
3     7.0   [Nelson, Jkhf]        0        1      Loka    Telagu  2020
4     NaN  [Dhanush, Gjkk]        0        1       Vip    Telagu  2022
5     7.0  [Rishab, Fghyg]        1        0  Bahubali     Hindi  2019
6     8.0      [NTR, Hytf]        1        1   Kantara   Kannada  2021
7     NaN  [Ranveer, Gfdr]        1        0       Rrr    Telagu  2024
8     6.0  [Salmaan, Iuyt]        0        1   Mastani     Hindi  2019
9     7.0  [SOmeone, Kiuy]        0        1   Shaitan     Hindi  2022

In [46]:
df=df.fillna(3)

In [47]:
df

   rating             Cast  Hotstar  Netflix     movie  Language  Year
0     8.0     [Yash, Rfst]        1        0       Kgf   Kannada  2018
1     6.0   [SRK, Sdfghjk]        1        1       Don     Hindi  2010
2     3.0   [Sudeep, Dfgh]        1        0      Mark  Kannnada  2020
3     7.0   [Nelson, Jkhf]        0        1      Loka    Telagu  2020
4     3.0  [Dhanush, Gjkk]        0        1       Vip    Telagu  2022
5     7.0  [Rishab, Fghyg]        1        0  Bahubali     Hindi  2019
6     8.0      [NTR, Hytf]        1        1   Kantara   Kannada  2021
7     3.0  [Ranveer, Gfdr]        1        0       Rrr    Telagu  2024
8     6.0  [Salmaan, Iuyt]        0        1   Mastani     Hindi  2019
9     7.0  [SOmeone, Kiuy]        0        1   Shaitan     Hindi  2022

In [48]:
df.to_csv('m1.csv', index=False)

In [49]:
df.to_excel('m2.xlsx')

In [50]:
df

   rating             Cast  Hotstar  Netflix     movie  Language  Year
0     8.0     [Yash, Rfst]        1        0       Kgf   Kannada  2018
1     6.0   [SRK, Sdfghjk]        1        1       Don     Hindi  2010
2     3.0   [Sudeep, Dfgh]        1        0      Mark  Kannnada  2020
3     7.0   [Nelson, Jkhf]        0        1      Loka    Telagu  2020
4     3.0  [Dhanush, Gjkk]        0        1       Vip    Telagu  2022
5     7.0  [Rishab, Fghyg]        1        0  Bahubali     Hindi  2019
6     8.0      [NTR, Hytf]        1        1   Kantara   Kannada  2021
7     3.0  [Ranveer, Gfdr]        1        0       Rrr    Telagu  2024
8     6.0  [Salmaan, Iuyt]        0        1   Mastani     Hindi  2019
9     7.0  [SOmeone, Kiuy]        0        1   Shaitan     Hindi  2022

In [51]:
df['Cast'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 10 entries, 0 to 9
Series name: Cast
Non-Null Count  Dtype
--------------  -----
10 non-null     object
dtypes: object(1)
memory usage: 208.0+ bytes

In [52]:
df['Cast']=df['Cast'].astype(str)

In [53]:
df['Cast'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 10 entries, 0 to 9
Series name: Cast
Non-Null Count  Dtype
--------------  -----
10 non-null     object
dtypes: object(1)
memory usage: 208.0+ bytes

In [54]:
df['Cast']=df['Cast'].str.strip('[]')

In [55]:
df['Cast']=df['Cast'].str.replace(',','-')

In [56]:
df['Cast']=df['Cast'].str.replace("'","")

In [57]:
df

   rating           Cast  Hotstar  Netflix     movie  Language  Year
0     8.0     Yash- Rfst        1        0       Kgf   Kannada  2018
1     6.0   SRK- Sdfghjk        1        1       Don     Hindi  2010
2     3.0   Sudeep- Dfgh        1        0      Mark  Kannnada  2020
3     7.0   Nelson- Jkhf        0        1      Loka    Telagu  2020
4     3.0  Dhanush- Gjkk        0        1       Vip    Telagu  2022
5     7.0  Rishab- Fghyg        1        0  Bahubali     Hindi  2019
6     8.0      NTR- Hytf        1        1   Kantara   Kannada  2021
7     3.0  Ranveer- Gfdr        1        0       Rrr    Telagu  2024
8     6.0  Salmaan- Iuyt        0        1   Mastani     Hindi  2019
9     7.0  SOmeone- Kiuy        0        1   Shaitan     Hindi  2022

### melt() is used to convert the columns into rows 

#### It is used to visualize the data

In [58]:
df1=pd.melt(df,id_vars=['movie','rating'],value_vars=['Hotstar','Netflix'],var_name='OTT',value_name='Available')

In [59]:
df1

       movie  rating      OTT  Available
0        Kgf     8.0  Hotstar          1
1        Don     6.0  Hotstar          1
2       Mark     3.0  Hotstar          1
3       Loka     7.0  Hotstar          0
4        Vip     3.0  Hotstar          0
5   Bahubali     7.0  Hotstar          1
6    Kantara     8.0  Hotstar          1
7        Rrr     3.0  Hotstar          1
8    Mastani     6.0  Hotstar          0
9    Shaitan     7.0  Hotstar          0
10       Kgf     8.0  Netflix          0
11       Don     6.0  Netflix          1
12      Mark     3.0  Netflix          0
13      Loka     7.0  Netflix          1
14       Vip     3.0  Netflix          1
15  Bahubali     7.0  Netflix          0
16   Kantara     8.0  Netflix          1
17       Rrr     3.0  Netflix          0
18   Mastani     6.0  Netflix          1
19   Shaitan     7.0  Netflix          1

In [60]:
df

   rating           Cast  Hotstar  Netflix     movie  Language  Year
0     8.0     Yash- Rfst        1        0       Kgf   Kannada  2018
1     6.0   SRK- Sdfghjk        1        1       Don     Hindi  2010
2     3.0   Sudeep- Dfgh        1        0      Mark  Kannnada  2020
3     7.0   Nelson- Jkhf        0        1      Loka    Telagu  2020
4     3.0  Dhanush- Gjkk        0        1       Vip    Telagu  2022
5     7.0  Rishab- Fghyg        1        0  Bahubali     Hindi  2019
6     8.0      NTR- Hytf        1        1   Kantara   Kannada  2021
7     3.0  Ranveer- Gfdr        1        0       Rrr    Telagu  2024
8     6.0  Salmaan- Iuyt        0        1   Mastani     Hindi  2019
9     7.0  SOmeone- Kiuy        0        1   Shaitan     Hindi  2022

## 08-06-26

In [61]:
df['Hotstar']+df['Netflix']

0    1
1    2
2    1
3    1
4    1
5    1
6    2
7    1
8    1
9    1
dtype: int64

In [62]:
df['tot_plts']=df['Hotstar']+df['Netflix']

In [63]:
df

   rating           Cast  Hotstar  Netflix     movie  Language  Year  tot_plts
0     8.0     Yash- Rfst        1        0       Kgf   Kannada  2018         1
1     6.0   SRK- Sdfghjk        1        1       Don     Hindi  2010         2
2     3.0   Sudeep- Dfgh        1        0      Mark  Kannnada  2020         1
3     7.0   Nelson- Jkhf        0        1      Loka    Telagu  2020         1
4     3.0  Dhanush- Gjkk        0        1       Vip    Telagu  2022         1
5     7.0  Rishab- Fghyg        1        0  Bahubali     Hindi  2019         1
6     8.0      NTR- Hytf        1        1   Kantara   Kannada  2021         2
7     3.0  Ranveer- Gfdr        1        0       Rrr    Telagu  2024         1
8     6.0  Salmaan- Iuyt        0        1   Mastani     Hindi  2019         1
9     7.0  SOmeone- Kiuy        0        1   Shaitan     Hindi  2022         1

In [64]:
df1

       movie  rating      OTT  Available
0        Kgf     8.0  Hotstar          1
1        Don     6.0  Hotstar          1
2       Mark     3.0  Hotstar          1
3       Loka     7.0  Hotstar          0
4        Vip     3.0  Hotstar          0
5   Bahubali     7.0  Hotstar          1
6    Kantara     8.0  Hotstar          1
7        Rrr     3.0  Hotstar          1
8    Mastani     6.0  Hotstar          0
9    Shaitan     7.0  Hotstar          0
10       Kgf     8.0  Netflix          0
11       Don     6.0  Netflix          1
12      Mark     3.0  Netflix          0
13      Loka     7.0  Netflix          1
14       Vip     3.0  Netflix          1
15  Bahubali     7.0  Netflix          0
16   Kantara     8.0  Netflix          1
17       Rrr     3.0  Netflix          0
18   Mastani     6.0  Netflix          1
19   Shaitan     7.0  Netflix          1

In [65]:
### Aggregate Function
df['rating'].count()

10

### Group By

In [66]:
df1

       movie  rating      OTT  Available
0        Kgf     8.0  Hotstar          1
1        Don     6.0  Hotstar          1
2       Mark     3.0  Hotstar          1
3       Loka     7.0  Hotstar          0
4        Vip     3.0  Hotstar          0
5   Bahubali     7.0  Hotstar          1
6    Kantara     8.0  Hotstar          1
7        Rrr     3.0  Hotstar          1
8    Mastani     6.0  Hotstar          0
9    Shaitan     7.0  Hotstar          0
10       Kgf     8.0  Netflix          0
11       Don     6.0  Netflix          1
12      Mark     3.0  Netflix          0
13      Loka     7.0  Netflix          1
14       Vip     3.0  Netflix          1
15  Bahubali     7.0  Netflix          0
16   Kantara     8.0  Netflix          1
17       Rrr     3.0  Netflix          0
18   Mastani     6.0  Netflix          1
19   Shaitan     7.0  Netflix          1

In [67]:
df1.groupby('OTT')

In [68]:
df1.groupby('OTT').agg({'rating':['max','mean'],'movie':'count'})

        rating      movie
           max mean count
OTT
Hotstar    8.0  5.8    10
Netflix    8.0  5.8    10